BCStheoryCriticalCurrentFit{32,64}.m: legend(Location -> Position)
According to Matlab/Octave documentation [1][2] to set the legend to
specific coordinates the property Position must be used instead of
Location. Location only supports string specifiers.

MatLab silently ignores this. However the problem does surface in
Octave, resulting in a fatal runtime error:

error: set: invalid value for radio property "location"
error: called from
    legend at line 289 column 10
    BCStheoryCriticalCurrentFit32 at line 50 column 10

[1]: https://nl.mathworks.com/help/matlab/ref/matlab.graphics.illustration.legend-properties.html
[2]: https://docs.octave.org/latest/Legend-Properties.html

Signed-off-by: Andrew Ammerlaan <andrewammerlaan@gentoo.org>